### ISSUE TITLE
/ (slash) at the beginning?

### ISSUE THREAD

**Issue by yonimoses** [mmiller42/html-webpack-externals-plugin#11]
Hi

Using the configuration mentioned here https://www.npmjs.com/package/html-webpack-externals-plugin#example , I'm getting an extra slash at the beginning of the of the <link> or <script> tag.
.e.g - `<link href="https://_SOME_URL" >`
becomes 
`<link href="/https://_SOME_URL" >`

with an extra slash before the https.. any idea or thoughts?

***** 
found the issue.. it was because of the publicPath of config.output.. is there anyway for this configuration to now affect the  html-webpack-externals-plugin ?

**Comment by marviobezerra** [comment]
I'm having the same issue. =/

**Comment by mmiller42** [comment]
This is fixed in v3, which is a complete rewrite (the previous versions just plain don't work, this is far from the only issue). Unfortunately it is an API rewrite, but it should be more stable.
