### ISSUE TITLE
Add support for Webpack 3.0

### ISSUE THREAD

**Issue by marviobezerra** [mmiller42/html-webpack-externals-plugin#12]
html-webpack-externals-plugin@3.3.1 requires a peer of webpack@^2.0.0 but none was installed.

**Comment by mmiller42** [comment]
Dang, I can't keep up with Webpack anymore ;D

Will address this weekend.

**Comment by mmiller42** [comment]
I removed the peerDependency since html-webpack-plugin already has webpack as a peerDependency anyway. Published in v3.3.4.
