### ISSUE TITLE
missing directory lib in npm package

### ISSUE THREAD

**Issue by puxxustc** [mmiller42/html-webpack-externals-plugin#13]
version 3.3.1

missing `lib` directory after install, so `require('html-webpack-externals-plugin')` will fail.

reproduce:
```bash
$ npm install html-webpack-externals-plugin
$ ls node_modules/html-webpack-externals-plugin
LICENSE  README.md  package.json  src
```

**Comment by mmiller42** [comment]
Yep, my bad, forgot to add a `.npmignore`. Fixed in 3.3.3.
