### ISSUE TITLE
Support SRI 

### ISSUE THREAD

**Issue by mohsen1** [mmiller42/html-webpack-externals-plugin#17]
I'm injecting CDN URLs with this plugin and want to add subresource integrity attribute to scripts as well.

**Comment by mmiller42** [comment]
Could you cover this by using the [`webpack-subresource-integrity`](https://www.npmjs.com/package/webpack-subresource-integrity) plugin alongside the html-webpack-externals-plugin?

**Comment by mohsen1** [comment]
When adding scripts from CDN, we need to provide the hash as well. It can't be generated from a URL.

**Comment by mmiller42** [comment]
Sorry for taking so long to get back to you on this issue; I'm thinking of adding a basic feature which would just allow you to add any attribute to the link or script element (e.g. another property `attributes`, which is just an object whose keys are attribute names and whose values are the attribute values). Would this be sufficient in this case?

**Comment by mohsen1** [comment]
I think so. You're not going to run the checks anyway. If you were then an api that has specific keys for hash would've made sense

**Comment by mmiller42** [comment]
This plugin actually wraps another plugin for injecting the asset tags into the HTML file, so I've opened a PR against that project [here](https://github.com/jharris4/html-webpack-include-assets-plugin/pull/14). The maintainer is pretty good with reviewing, so with any luck, I should be able to roll out this feature over the next few days.

**Comment by mmiller42** [comment]
@brenoc adding you here in case you were interested in subscribing to this issue when it is fixed.

**Comment by mmiller42** [comment]
Released in [v3.6.0](https://github.com/mmiller42/html-webpack-externals-plugin/releases/tag/v3.6.0).

**Comment by mmiller42** [comment]
I’m going to close this issue since I think it’s resolved but let me know if it doesn’t cover any use cases or there are bugs with the implementation.

**Comment by klzns** [comment]
@mmiller42 thanks, you're awesome!
