### ISSUE TITLE
Support cross-origin attribute to CDN URLs

### ISSUE THREAD

**Issue by klzns** [mmiller42/html-webpack-externals-plugin#18]
I'm using this plugin to specify that React will be loaded from a CDN, like so:

```js
new HtmlWebpackExternalsPlugin({
  externals: [
    {
      module: 'react',
      entry: 'https://unpkg.com/react@15.6.1/dist/react.min.js',
      global: 'React'
    },
    {
      module: 'react-dom',
      entry: 'https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js',
      global: 'ReactDOM'
    }
  ]
}),
```

It would be nice if I could specify a new option, like `"crossOrigin": true` that could add the attribute "cross-origin" to the script tag.

To understand how that is important:
https://twitter.com/dan_abramov/status/893099358484353024

I tried to use this plugin: https://github.com/dentuzhik/html-webpack-crossorigin-plugin
But it adds the attribute to all the <script> tags and I think that's not ideal.

**Comment by mmiller42** [comment]
Sorry, I've been neglecting the issues on this repo for a while, but I did want to take a closer look at these. Would I be correct in assuming that all this really needs is the ability to add essentially any attribute to the script or link tag that is being injected? I'd like to keep this generic as possible, and I'm thinking perhaps we just need another option that lets you add attribute/value pairs to the element (e.g. `attrs: { crossorigin: '' }`).

**Comment by klzns** [comment]
@mmiller42 I think that solution would be great as well.

**Comment by mmiller42** [comment]
Great! In that case, I'm going to close this issue because this same solution will also solve #17, so I'll just keep track of it there.
