### ISSUE TITLE
Can not work when set webpack config of output public path

### ISSUE THREAD

**Issue by giiska** [mmiller42/html-webpack-externals-plugin#2]
The html-webpack-plugin will prepend the public path to all chunk files when set public path.

**Comment by jonathanasquier** [comment]
+1

**Comment by Dreem-Devices** [comment]
+1, anyone has found a solution to this issue?
We cannot use this plugin if it preprends publicPath for cdn...

**Comment by andrew-luminal** [comment]
+1 having this problem too

**Comment by mmiller42** [comment]
I just released 3.0, which is a complete rewrite and instead solves most of these discrepancies by bundling two other plugins, the CopyWebpackPlugin and HtmlWebpackIncludeAssetsPlugin. It's brand new and I'm sure it has its issues, but you're welcome to give it a try and open up any new issues if you run into problems.
