### ISSUE TITLE
Support context in CopyWebpackPlugin

### ISSUE THREAD

**Issue by BarinDwalin** [mmiller42/html-webpack-externals-plugin#25]
Please add a **context** attribute to the CopyWebpackPlugin. In my case I need to change the node_modules path.

**Comment by mmiller42** [comment]
@tsachis @DJPorv @BarinDwalin

Sorry for taking so long, but this is finally released in [v3.7.0](https://github.com/mmiller42/html-webpack-externals-plugin/releases/tag/v3.7.0).

There is now the ability to specify `cwpOptions` on the top level config object, which forwards options in as the second parameter to the copy-webpack-plugin constructor, as well as to add/overwrite properties on each of the pattern objects passed in as the first parameter via `cwpPatternConfig` on each module entry point or supplement. See the readme for details and examples.
