### ISSUE TITLE
force external to use <link>

### ISSUE THREAD

**Issue by mo22** [mmiller42/html-webpack-externals-plugin#6]
please provide some option (type: 'link' or link: true ..) to support <link> externals that do not end in .css like:

https://fonts.googleapis.com/css?family=Material+Icons

currently using workaround:

https://fonts.googleapis.com/css?family=Material+Icons&.css

**Comment by mo22** [comment]
also in html-webpack-plugin-alter-asset-tags please replace
`callback()` with `callback(null, pluginArgs);`
that solves a deprecation notice `...without returning a result is deprecated.`

**Comment by mo22** [comment]
also, the following code seems to remove link elements and reset them to {} causing a <> in the output:
`
            //make sure that the order of lib css before the css of module
            for( i = 0, len = extractedCss.length; i < len; i++ ){
                extractedCss[i] = Object.assign({}, pluginArgs.head.splice(extractedCss[i], 1)[0]);
            }
`
I assume it should be replaced with:
`
            //make sure that the order of lib css before the css of module
            for( i = 0, len = extractedCss.length; i < len; i++ ){
                extractedCss[i] = Object.assign({}, pluginArgs.head.splice(extractedCss[0], 1)[0]);
            }
`
The head.splice removes the item, so additionally incrementing i seems wrong.


>

**Comment by mmiller42** [comment]
I am currently working on this issue and have created a branch (https://github.com/mmiller42/html-webpack-externals-plugin/compare/override-type?ts=2). However, it is contingent on my pull request into html-webpack-include-assets-plugin, which adds the ability to manually specify asset type (https://github.com/jharris4/html-webpack-include-assets-plugin/pull/8).

**Comment by mmiller42** [comment]
Resolved in [v3.3.0](https://github.com/mmiller42/html-webpack-externals-plugin/releases/tag/v3.3.0)

**Comment by mo22** [comment]
Hey thank you very much!
